#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreProducts_WPF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StoreDb")]
	public partial class StoreDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public StoreDataClassesDataContext() : 
				base(global::StoreProducts_WPF.Properties.Settings.Default.StoreDbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StoreDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoreDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoreDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoreDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product
	{
		
		private int _Id;
		
		private string _Url;
		
		private string _Price;
		
		private string _Name;
		
		private string _Image;
		
		private string _BadgeType;
		
		private string _ProductType;
		
		private int _ColourWayId;
		
		private bool _IsSale;
		
		private string _ReducedPrice;
		
		private bool _HasMultiplePrices;
		
		private bool _IsOutlet;
		
		private bool _IsSellingFast;
		
		private int _PageNumber;
		
		private int _TileId;
		
		private string _Colour;
		
		private string _CategoryName;
		
		private string _BaseUrl;
		
		private string _MainCategory;
		
		private string _BrandName;
		
		private string _ProductRating;
		
		private string _ProductCode;
		
		private string _ProductDescription;
		
		public Product()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BadgeType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BadgeType
		{
			get
			{
				return this._BadgeType;
			}
			set
			{
				if ((this._BadgeType != value))
				{
					this._BadgeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColourWayId", DbType="Int NOT NULL")]
		public int ColourWayId
		{
			get
			{
				return this._ColourWayId;
			}
			set
			{
				if ((this._ColourWayId != value))
				{
					this._ColourWayId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSale", DbType="Bit NOT NULL")]
		public bool IsSale
		{
			get
			{
				return this._IsSale;
			}
			set
			{
				if ((this._IsSale != value))
				{
					this._IsSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReducedPrice", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ReducedPrice
		{
			get
			{
				return this._ReducedPrice;
			}
			set
			{
				if ((this._ReducedPrice != value))
				{
					this._ReducedPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasMultiplePrices", DbType="Bit NOT NULL")]
		public bool HasMultiplePrices
		{
			get
			{
				return this._HasMultiplePrices;
			}
			set
			{
				if ((this._HasMultiplePrices != value))
				{
					this._HasMultiplePrices = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOutlet", DbType="Bit NOT NULL")]
		public bool IsOutlet
		{
			get
			{
				return this._IsOutlet;
			}
			set
			{
				if ((this._IsOutlet != value))
				{
					this._IsOutlet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSellingFast", DbType="Bit NOT NULL")]
		public bool IsSellingFast
		{
			get
			{
				return this._IsSellingFast;
			}
			set
			{
				if ((this._IsSellingFast != value))
				{
					this._IsSellingFast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageNumber", DbType="Int NOT NULL")]
		public int PageNumber
		{
			get
			{
				return this._PageNumber;
			}
			set
			{
				if ((this._PageNumber != value))
				{
					this._PageNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TileId", DbType="Int NOT NULL")]
		public int TileId
		{
			get
			{
				return this._TileId;
			}
			set
			{
				if ((this._TileId != value))
				{
					this._TileId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colour", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Colour
		{
			get
			{
				return this._Colour;
			}
			set
			{
				if ((this._Colour != value))
				{
					this._Colour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseUrl", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BaseUrl
		{
			get
			{
				return this._BaseUrl;
			}
			set
			{
				if ((this._BaseUrl != value))
				{
					this._BaseUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainCategory", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MainCategory
		{
			get
			{
				return this._MainCategory;
			}
			set
			{
				if ((this._MainCategory != value))
				{
					this._MainCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				if ((this._BrandName != value))
				{
					this._BrandName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductRating", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ProductRating
		{
			get
			{
				return this._ProductRating;
			}
			set
			{
				if ((this._ProductRating != value))
				{
					this._ProductRating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDescription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ProductDescription
		{
			get
			{
				return this._ProductDescription;
			}
			set
			{
				if ((this._ProductDescription != value))
				{
					this._ProductDescription = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
